In [1]:
%timeit

from pycaret.classification import *
import pandas as pd
import numpy as np
from catboost import Pool, CatBoostClassifier
from xgboost import XGBClassifier

data = pd.read_csv('Collection/titanic_comp/Train_clean.csv')

grid = setup(data, 
             target='Survived', 
             log_experiment=True, 
            
             silent=True, 
             verbose=True,
             log_plots=True,
             n_jobs=1)

In [8]:
analyze = compare_models()

In [9]:
from sklearn.linear_model import RidgeClassifier

rc = tune_model(RidgeClassifier(),n_iter=50,search_library='optuna', search_algorithm='tpe', tuner_verbose=True, verbose=True, early_stopping='asha',early_stopping_max_iters=15)

In [10]:
print(rc)

RidgeClassifier(alpha=1.8276256508943347, class_weight=None, copy_X=True,
                fit_intercept=False, max_iter=None, normalize=False,
                random_state=None, solver='auto', tol=0.001)

In [29]:
cat = tune_model(CatBoostClassifier(),n_iter=50,search_library='optuna', search_algorithm='tpe', tuner_verbose=True, verbose=True, early_stopping='asha',early_stopping_max_iters=10)

IntProgress(value=0, description='Processing: ', max=7)

Initiated  . . . . . . . . . . . . . . . . . .                   06:03:56
Status     . . . . . . . . . . . . . . . . . .  Searching Hyperparameters
Estimator  . . . . . . . . . . . . . . . . . .        CatBoost Classifier

Empty DataFrame
Columns: [Accuracy, AUC, Recall, Prec., F1, Kappa, MCC]
Index: []

In [18]:
test = pd.read_csv('Collection/titanic_comp/test_clean.csv')

In [12]:
pred_holdout = predict_model(rc)

In [13]:
jack = finalize_model(rc)

In [14]:
print(jack)

RidgeClassifier(alpha=1.8276256508943347, class_weight=None, copy_X=True,
                fit_intercept=False, max_iter=None, normalize=False,
                random_state=None, solver='auto', tol=0.001)

In [19]:
y_pred = predict_model(jack, data = test)

In [20]:
print(len(y_pred))

418

In [25]:
y_pred = y_pred.rename(columns={'Label':'Survived'})

In [27]:
test_passenger_df = pd.read_csv('Collection/titanic_comp/test.csv')
tree = test_passenger_df.PassengerId

submission = pd.DataFrame()
submission['PassengerID'] = tree.tolist()
submission['Survived'] = y_pred.Survived.tolist()

submission.head()

SyntaxError: invalid syntax (<ipython-input-27-0886a078d278>, line 8)

In [28]:
submission.to_csv("Collection/titanic_comp/Pycaret-submission.csv", index=False)